import { useState, useEffect, useCallback, useRef } from "react";
import { Download, WifiOff, X, RefreshCw } from "lucide-react";

/* ─── Types ─── */
interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>;
  userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
}

/* ─── PWA Registration ─── */
function usePWARegistration() {
  const [needRefresh, setNeedRefresh] = useState(false);
  const registrationRef = useRef<ServiceWorkerRegistration | null>(null);

  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    // Register SW via the virtual module generated by vite-plugin-pwa
    // In production, the plugin injects the SW automatically.
    // For dev, we handle it gracefully.
    const registerSW = async () => {
      try {
        const reg = await navigator.serviceWorker.register("/push-handler.js", {
          scope: "/",
          type: "classic",
        });
        registrationRef.current = reg;

        reg.addEventListener("updatefound", () => {
          const newSW = reg.installing;
          if (!newSW) return;
          newSW.addEventListener("statechange", () => {
            if (newSW.state === "installed" && navigator.serviceWorker.controller) {
              setNeedRefresh(true);
            }
          });
        });
      } catch {
        // SW registration failed (expected in dev without vite-plugin-pwa dev support)
      }
    };

    registerSW();
  }, []);

  const updateSW = useCallback(() => {
    const reg = registrationRef.current;
    if (reg?.waiting) {
      reg.waiting.postMessage({ type: "SKIP_WAITING" });
      window.location.reload();
    }
  }, []);

  return { needRefresh, updateSW };
}

/* ─── Offline Detection ─── */
function useOnlineStatus() {
  const [isOnline, setIsOnline] = useState(
    typeof navigator !== "undefined" ? navigator.onLine : true
  );

  useEffect(() => {
    const goOnline = () => setIsOnline(true);
    const goOffline = () => setIsOnline(false);
    window.addEventListener("online", goOnline);
    window.addEventListener("offline", goOffline);
    return () => {
      window.removeEventListener("online", goOnline);
      window.removeEventListener("offline", goOffline);
    };
  }, []);

  return isOnline;
}

/* ─── Install Prompt ─── */
function useInstallPrompt() {
  const [installPrompt, setInstallPrompt] = useState<BeforeInstallPromptEvent | null>(null);
  const [isInstalled, setIsInstalled] = useState(false);

  useEffect(() => {
    // Check if already installed (standalone mode)
    if (window.matchMedia("(display-mode: standalone)").matches) {
      setIsInstalled(true);
      return;
    }

    const handler = (e: Event) => {
      e.preventDefault();
      setInstallPrompt(e as BeforeInstallPromptEvent);
    };

    window.addEventListener("beforeinstallprompt", handler);
    window.addEventListener("appinstalled", () => {
      setIsInstalled(true);
      setInstallPrompt(null);
    });

    return () => window.removeEventListener("beforeinstallprompt", handler);
  }, []);

  const promptInstall = useCallback(async () => {
    if (!installPrompt) return;
    await installPrompt.prompt();
    const result = await installPrompt.userChoice;
    if (result.outcome === "accepted") {
      setIsInstalled(true);
    }
    setInstallPrompt(null);
  }, [installPrompt]);

  return { canInstall: !!installPrompt && !isInstalled, isInstalled, promptInstall };
}

/* ─── Main PWA Manager Component ─── */
export function PWAManager() {
  const isOnline = useOnlineStatus();
  const { needRefresh, updateSW } = usePWARegistration();
  const { canInstall, promptInstall } = useInstallPrompt();
  const [dismissedInstall, setDismissedInstall] = useState(false);
  const [showOffline, setShowOffline] = useState(false);

  // Delay showing offline banner to avoid flash on slow connections
  useEffect(() => {
    if (!isOnline) {
      const t = setTimeout(() => setShowOffline(true), 1500);
      return () => clearTimeout(t);
    }
    setShowOffline(false);
  }, [isOnline]);

  return (
    <>
      {/* ═══ Offline Banner ═══ */}
      {showOffline && (
        <div
          className="fixed top-0 left-0 right-0 z-[9999] flex items-center justify-center gap-2 px-4 py-2"
          style={{
            background: "linear-gradient(135deg, #54565B 0%, #3a3c40 100%)",
            color: "#fff",
            fontSize: "13px",
            fontWeight: 500,
            fontFamily: "'Encode Sans', sans-serif",
            paddingTop: "max(8px, env(safe-area-inset-top))",
            animation: "slideDown 0.3s ease-out",
          }}
        >
          <WifiOff size={14} strokeWidth={2.5} />
          <span>Sin conexión — Modo offline activo</span>
          <button
            onClick={() => setShowOffline(false)}
            className="ml-auto p-0.5 rounded-full"
            style={{ background: "rgba(255,255,255,0.15)" }}
          >
            <X size={12} />
          </button>
        </div>
      )}

      {/* ═══ Update Available Banner ═══ */}
      {needRefresh && (
        <div
          className="fixed bottom-20 left-4 right-4 z-[9999] flex items-center gap-3 px-4 py-3 rounded-2xl"
          style={{
            background: "linear-gradient(135deg, #AB1738 0%, #8B1028 100%)",
            color: "#fff",
            fontFamily: "'Encode Sans', sans-serif",
            boxShadow: "0 8px 32px rgba(171,23,56,0.3), 0 2px 8px rgba(0,0,0,0.15)",
            animation: "slideUp 0.4s ease-out",
          }}
        >
          <RefreshCw size={18} className="shrink-0" />
          <div className="flex-1 min-w-0">
            <div style={{ fontSize: "14px", fontWeight: 600 }}>Actualización disponible</div>
            <div style={{ fontSize: "12px", opacity: 0.85 }}>Nueva versión lista para instalar</div>
          </div>
          <button
            onClick={updateSW}
            className="shrink-0 px-3 py-1.5 rounded-xl"
            style={{
              background: "rgba(255,255,255,0.2)",
              backdropFilter: "blur(8px)",
              fontSize: "13px",
              fontWeight: 600,
              border: "1px solid rgba(255,255,255,0.25)",
            }}
          >
            Actualizar
          </button>
        </div>
      )}

      {/* ═══ Install Prompt ═══ */}
      {canInstall && !dismissedInstall && (
        <div
          className="fixed bottom-20 left-4 right-4 z-[9998] flex items-center gap-3 px-4 py-3 rounded-2xl"
          style={{
            background: "linear-gradient(135deg, rgba(255,255,255,0.95) 0%, rgba(255,255,255,0.9) 100%)",
            backdropFilter: "blur(20px) saturate(180%)",
            fontFamily: "'Encode Sans', sans-serif",
            boxShadow: "0 8px 32px rgba(0,0,0,0.12), 0 2px 8px rgba(0,0,0,0.06)",
            border: "1px solid rgba(0,0,0,0.06)",
            animation: "slideUp 0.4s ease-out",
          }}
        >
          <div
            className="shrink-0 w-10 h-10 rounded-xl flex items-center justify-center"
            style={{ background: "linear-gradient(135deg, #AB1738, #8B1028)" }}
          >
            <Download size={18} color="#fff" />
          </div>
          <div className="flex-1 min-w-0">
            <div style={{ fontSize: "14px", fontWeight: 600, color: "#1C1C1E" }}>
              Instalar PC Tamaulipas
            </div>
            <div style={{ fontSize: "12px", color: "#6E6E73" }}>
              Acceso rápido desde tu pantalla de inicio
            </div>
          </div>
          <button
            onClick={promptInstall}
            className="shrink-0 px-3 py-1.5 rounded-xl"
            style={{
              background: "#AB1738",
              color: "#fff",
              fontSize: "13px",
              fontWeight: 600,
            }}
          >
            Instalar
          </button>
          <button
            onClick={() => setDismissedInstall(true)}
            className="shrink-0 p-1"
            style={{ color: "#6E6E73" }}
          >
            <X size={16} />
          </button>
        </div>
      )}

      {/* ═══ Animations ═══ */}
      <style>{`
        @keyframes slideDown {
          from { transform: translateY(-100%); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }
        @keyframes slideUp {
          from { transform: translateY(20px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }
      `}</style>
    </>
  );
}